name: Build all contents

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.x
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install LaTeX and fonts
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install \
            msttcorefonts \
            ttf-mscorefonts-installer \
            texlive-fonts-recommended \
            texlive-lang-greek \
            texlive-latex-base \
            texlive-latex-recommended

      - name: Instal pandoc and pandoc-crossref
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.17.0.1/pandoc-2.17.0.1-1-amd64.deb
          sudo dpkg -i pandoc-2.17.0.1-1-amd64.deb
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.12.2/pandoc-crossref-Linux.tar.xz
          tar -xvf pandoc-crossref-Linux.tar.xz
          sudo mv pandoc-crossref /bin

      - name: Build
        run: make --silent -j

      - name: Move data
        run: |
          mkdir dist
          mkdir dist/paper
          cp -r output/ dist/
          cp -r figure/ dist/
          cp paper/*.pdf dist/paper
          cp paper/*.docx dist/paper

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built_contents
          path: dist/
