name: Build all contents

on:
  workflow_call:

jobs:
  build:
    needs: build-and-push-image # Ensure that the image is built before running the build job
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:main
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install LaTeX and fonts
        run: |
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install \
            msttcorefonts \
            ttf-mscorefonts-installer \
            texlive-fonts-recommended \
            texlive-lang-greek \
            texlive-latex-base \
            texlive-latex-recommended

      - name: Instal pandoc and pandoc-crossref
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.17.0.1/pandoc-2.17.0.1-1-amd64.deb
          sudo dpkg -i pandoc-2.17.0.1-1-amd64.deb
          wget https://github.com/lierdakil/pandoc-crossref/releases/download/v0.3.12.2/pandoc-crossref-Linux.tar.xz
          tar -xvf pandoc-crossref-Linux.tar.xz
          sudo mv pandoc-crossref /bin

      - name: Build
        run: make --silent -j

      - name: Move data
        run: |
          mkdir dist
          mkdir dist/paper
          cp -r output/ dist/
          cp -r figure/ dist/
          cp paper/*.pdf dist/paper
          cp paper/*.docx dist/paper

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built_contents
          path: dist/

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
