name: Continuous Integration

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/builder.yaml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Black
        if: always()
        run: black --check .

      - name: Run flake8
        if: always()
        run: autoflake --check-diff --recursive --remove-all-unused-imports .

      - name: Run isort
        if: always()
        run: isort --check .
